### ISSUE TITLE
Separate Arrow work into its own sub-module in Iceberg

### ISSUE THREAD

**Issue by anjalinorwood** [apache/incubator-iceberg#522] opened 2019-10-08 17:22 UTC
A few Arrow related changes (outlined below) were needed to get better performance with Vectorized Iceberg Reads. It would be good to get these issues fixed in Arrow, but meanwhile these Arrow-related fixes in Iceberg should be separated out in its own sub-module.
The changes are: 
1) Iceberg Vectorized Read code path maintains a separate validity vector (as array of booleans) on heap and consults this validity vector before accessing the data value. Arrow validity vector continues to get populated for correctness.
2) Arrow checks to check for null values are disabled.
3) 'Invalid memory access' checks are disabled.

**Comment by prodeezy** [comment] 2019-10-09 05:38
@anjalinorwood  isn't this same as https://github.com/apache/incubator-iceberg/issues/311 ?

**Comment by prodeezy** [comment] 2019-11-08 01:24
@anjalinorwood i'm thinking of taking this up.

**Comment by anjalinorwood** [comment] 2019-11-08 15:46
Great @prodeezy. @samarthjain , can you please sync with Gautam to avoid any duplicate work? Thank you both.

**Comment by samarthjain** [comment] 2019-11-14 22:25
@prodeezy - #311 looks like a duplicate of this one.

**Comment by prodeezy** [comment] 2019-12-18 17:17
https://github.com/apache/incubator-iceberg/issues/311 and https://github.com/apache/incubator-iceberg/pull/702 address this issue. Can close this? @rdblue @samarthjain @anjalinorwood

**Comment by rdblue** [comment] 2019-12-18 17:22
Closing. Thanks @prodeezy and @samarthjain!

**Closed by rdblue** 2019-12-18 17:22 UTC
