### ISSUE TITLE
Conversions#fromPartitionString() could not convert String of timestamp-like format to Integer

### ISSUE THREAD

**Issue by waterlx** [apache/incubator-iceberg#483] opened 2019-09-18 06:51 UTC
Suppose that I have a partition spec using "hour" transform, like:
```scala
val partitionSpec = PartitionSpec.builderFor(schema).hour("event_time").identity("level").build() 
 // "event_time" is a TimestampType
```
Then I use DeleteFiles.builder to build a DeleteFile, like
```scala
val fileToDelete1 = DataFiles.builder(partitionSpec)
      .withPartitionPath("event_time_hour=2020-01-01-01/level=ERROR")
      ...
```
The request is rejected by 
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "2019-01-02-01"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at org.apache.iceberg.types.Conversions.fromPartitionString(Conversions.java:50)
	at org.apache.iceberg.DataFiles.fillFromPath(DataFiles.java:83)
	at org.apache.iceberg.DataFiles.access$200(DataFiles.java:36)
	at org.apache.iceberg.DataFiles$Builder.withPartitionPath(DataFiles.java:292)
```
Integer.valueOf() could not handle “2020-01-01-01". See https://github.com/apache/incubator-iceberg/blob/433f169e9d0b10688d395abde64c4b6461d35ca9/api/src/main/java/org/apache/iceberg/types/Conversions.java#L50
ParitionSpec.Builder#month() has the same issue when trying to handle a String like "2019-01".

**Comment by waterlx** [comment] 2019-09-18 07:36
@aokolnychyi @rdblue does it make any sense to you?

**Comment by rdblue** [comment] 2019-09-18 16:58
@waterlx, `withPartitionPath` is only public to support importing existing Hive table files. Iceberg considers building a partition path string a one-way conversion. If you want to parse partition paths, you should use your own parsing logic and pass a `StructLike` to the builder.

**Comment by chenjunjiedada** [comment] 2019-09-19 13:17
@waterlx, Do you why we get an Integer type from the TimeStamp type partition? Also why you using a date value for timestamp type?

**Comment by rdblue** [comment] 2019-09-19 17:51
@chenjunjiedada, the format here is what Iceberg produces for an hour partition value. Iceberg internally stores the values as the number of hours from 1970-01-01 hour 0, but that's not user-friendly. So it gets converted to YYYY-MM-DD-HH in the partition path.

The problem is that Iceberg does not _parse_ these values because creating a file path is a one-way conversion. To delete these files, you can pass the file path directly to `DeleteFiles`, or you can get a `DataFile` instance from `FindFiles` and pass that.

You could also come up with a way to parse these hour values, but we don't recommend doing this in general because of string escaping issues. That's why Iceberg considers the conversion one-way.

**Comment by chenjunjiedada** [comment] 2019-09-20 03:11
@rdblue, Thanks for the elaboration.

So if we want to use an `hour` partition filed of `YYYY-MM-DD-HH` format in PartitionSpec.  Either we need to transform the string to a timestamp value at first, for example, `event_time_hour=1568892724618` to `withPartitionPath`.  Or we can add a function which produces a `PartitionData`  from the string. Am I correct?

**Comment by rdblue** [comment] 2019-09-20 16:42
@chenjunjiedada, you should not parse strings into partition data. Parsing partition strings is an anti-pattern because there are many cases that will cause you to get corrupted data, like not handling escaping correctly.

Instead of parsing partition strings, you can delete by path or you can get a `DataFile` instance from the table using `FindFiles`.

**Comment by chenjunjiedada** [comment] 2019-09-21 05:37
Understood now. Thanks again.

**Comment by rdblue** [comment] 2019-09-21 21:27
Great, I'm going to close this then. Thanks!

**Closed** 2019-09-21 21:27 UTC
