### ISSUE TITLE
TestScanSummary appears to be flaky

### ISSUE THREAD

**Issue by holdenk** [apache/incubator-iceberg#494] opened 2019-09-24 20:04 UTC
I was building Apache Icerberg for the first time and I ran into a test failure with `TestScanSummary`. Re-running the test with debugging information on, or by its self it started passing. Looking at the fix of waiting for the system clock to change by at least 1 tick I think there maybe needs to be more separation for the test not to be flaky.

More generally I'm getting really confusing information from the internet of if the way how we're attempting to use currentTimeMillis is safe, e.g. seems like it may not be monotonically increasing but that might just be really old kernels.

**Comment by rdblue** [comment] 2019-09-25 16:47
Which test cases were flaky? We added a fix for this a little while ago: https://github.com/apache/incubator-iceberg/commit/029313ec60b48b00c28db1820a8a63a6e9b1964d#diff-e631e40a3e4d7247bae10d3de37d0df1

**Comment by holdenk** [comment] 2019-09-25 18:38
I know (that’s why I included the git hash I was on when I noticed this) but it still seems like it flakes. The only reason I could guess that it might flake is multi-threaded time reporting not moving consistently forward. There totally could be something else (maybe I had an NTP event during the test and time moved backwards?) but I’m not really sure.

I can run the test in a loop with a shell script and measure the flakiness as a next step?

**Comment by holdenk** [comment] 2019-09-25 18:39
Oh oops I didn’t include the git hash, I thought I did let me add that.

**Comment by holdenk** [comment] 2019-09-25 18:47
I was at f7bc07d58957d088c766cba845a630594c99f0c8 which already includes 029313ec60b48b00c28db1820a8a63a6e9b1964d

This came from my first setting up & testing of iceberg which I streamed ( https://www.youtube.com/watch?v=axzknSKHzWY&feature=youtu.be )

**Comment by aokolnychyi** [comment] 2019-09-25 18:51
I also saw a failure in our CI pipelines after the fix above.

**Comment by rdblue** [comment] 2019-09-30 17:15
Which test case was the problem? Was it the same, or did I miss one?

**Comment by aokolnychyi** [comment] 2019-09-30 17:56
It was the same as before. I cannot reproduce it locally but it failed frequently in CI.

**Comment by holdenk** [comment] 2019-09-30 18:19
I think maybe requiring a minimum time unit to pass might be better than just not having the times be equal. But I'm not sure if that is a gaurantee in iceberg we should be testing for or not @rdblue ?

**Comment by rdblue** [comment] 2019-09-30 18:25
Yeah, we can update that logic to be a bit more paranoid about values we get from System.currentTimeMillis instead of using equality. @holdenk, would you like to open a PR for that? If not, I can fix it sometime today.

**Comment by holdenk** [comment] 2019-09-30 18:26
If you don't mind a bit of a wait it would be a fun first PR for me to do, I've just meetings most of the day so I'd probably do it tomorrow.

**Comment by aokolnychyi** [comment] 2019-11-14 19:28
This was fixed in #641. @holdenk, please reopen if the fix wasn't sufficient.

**Closed by aokolnychyi** 2019-11-14 19:28 UTC
