### ISSUE TITLE
Dropping a partition column throws NPE

### ISSUE THREAD

**Issue by pprudhvi** [apache/incubator-iceberg#700] opened 2019-12-13 12:09 UTC
`table.updateSchema().deleteColumn(col1).commit()` throws NPE if the table is partitioned by `col1`
Stacktrace:
`Caused By (java.lang.NullPointerException) null
    org.apache.iceberg.PartitionSpec.checkCompatibility():485
    org.apache.iceberg.TableMetadata.updateSchema():285
    org.apache.iceberg.SchemaUpdate.commit():209`

**Comment by jerryshao** [comment] 2019-12-16 12:10
@pprudhvi would you please provide a simple reproducible code, thanks.

**Comment by pprudhvi** [comment] 2019-12-16 16:42
`public static void main(String... args) {
    IcebergTableOperations tableOperations = new IcebergTableOperations(new Path("/tmp/student"), new Configuration());
    Schema schema = new Schema(Types.NestedField.required(1, "id", Types.IntegerType.get()),
        Types.NestedField.required(2, "name", Types.IntegerType.get()));
    PartitionSpec partitionSpec = PartitionSpec.builderFor(schema).identity("id").build();
    TableMetadata metadata = TableMetadata.newTableMetadata(tableOperations, schema, partitionSpec, "/tmp/student");
    Transactions.createTableTransaction(tableOperations, metadata).commitTransaction();
    Transactions.newTransaction(tableOperations).updateSchema().deleteColumn("id").commit();
  }`

**Comment by rdblue** [comment] 2019-12-18 21:46
Looks like `checkCompatibility` needs to be updated to throw an exception with a better error message when a column is not present. @pprudhvi, would you like to submit a PR to fix this?

**Comment by pprudhvi** [comment] 2019-12-19 05:55
yes, I can submit a patch but it won't fix the issue with dropping a partition colum. Or do we need to follow a different path to drop such columns - update partition spec first and then call deleteColumn ?

**Comment by rdblue** [comment] 2019-12-27 23:20
@pprudhvi, I think #716 is going to add a nice error message for this. #532 added a check to the validation, but that error message was confusing.

**Comment by rdblue** [comment] 2019-12-27 23:21
#714 tracks the error message, and #532 fixed the NPE this reported so I'm going to close this.

**Closed by rdblue** 2019-12-27 23:21 UTC
